### ISSUE TITLE
关于图片缓存可用的改进方案

### ISSUE THREAD

**Issue by EvolvedGhost** [Shennoter/ApexRankLookUp#10]
图片缓存目前全部存储于`/data/pers.shennoter.ranklookup`目录下，图片缓存也有可能过期或者失效，因此可以新增一个可选的手动清除缓存的指令来清空`/data/pers.shennoter.ranklookup`目录以实现清理图片缓存以避免未来可能出现的一些缓存问题。

作者有空的话可以给每个图片记录缓存时间并在某段时间后进行自动删除

**Comment by Shennoter** [comment]
缓存清理功能已经实现，分为手动和自动，准备跟新闻、猎杀排行榜和服务器状态一起更新
