### ISSUE TITLE
新版本ApexLookUp - v1.4.0-pre的使用情况

### ISSUE THREAD

**Issue by SVIPNB** [Shennoter/ApexRankLookUp#11]
1.在使用/apexadd id svipnb12138后使用/apexremove id svipnb12138，并没有取消对svipnb12138的监听，控制台每隔15分钟依旧显示“完成一次对svipnb12138的监听”。
2.、config.yml中mapRotationReminder: true，在群里输入/apexadd map后，确实显示“已添加对群号xxxxxxxxx的地图轮换提醒”，但是过了三个小时，群里并没有提醒

**Comment by Shennoter** [comment]
上传了新版本，重新下载试试

**Comment by Shennoter** [comment]
是协程取消的问题，等下我修改一下

**Comment by SVIPNB** [comment]
好

**Comment by Shennoter** [comment]
重新上传了，你再下载试试

**Comment by SVIPNB** [comment]
![Screenshot_2022-05-26-10-57-46-987-edit_com tencent mobileqq](https://user-images.githubusercontent.com/105286806/170406517-59944098-7886-4328-b746-ced0e504ea6c.jpg)
昨天晚上倒是提醒了，今天早上下载了新发布的，八点半提醒了一次之后，就没反应了

**Comment by Shennoter** [comment]
我的机器人每次都提醒了，看看你的data文件夹里map.time的内容和Reminder.json的内容

**Comment by SVIPNB** [comment]
我知道了，原来是我服务器死机了，现在应该好了😑

**Comment by Shennoter** [comment]
😨

**Comment by SVIPNB** [comment]
哈哈哈哈哈(掩饰尴尬)现在好了，刚才就当无事发生过
![Screenshot_2022-05-26-11-30-56-854_com tencent mobileqq](https://user-images.githubusercontent.com/105286806/170410558-9274c632-04de-4be1-a73a-a300decc5d94.png)
