### ISSUE TITLE
[Bug]地图轮换提醒错误

### ISSUE THREAD

**Issue by Evyde** [Shennoter/ApexRankLookUp#15]
## 问题描述

<img width="309" alt="image" src="https://user-images.githubusercontent.com/9302540/173987444-5aa3d4a0-e65a-4138-a47b-a249503537ab.png">

如图，当配置设置如上时，应该跳过风暴点的提醒，但实际上跳过的是风暴点的下一张地图的提醒（奥林匹斯）。

## 原因分析

在`MapReminder.kt`中：
https://github.com/Shennoter/ApexRankLookUp/blob/8e96b0839f1fdf0f098c7d818e63e63b1fe164aa/src/main/kotlin/utils/MapReminder.kt#L77-L79
if判断的是当前地图是否在提醒列表中，但是条件成立后，提醒的却是“当前地图被轮换掉”而非“当前地图开始轮换”。

## 修改建议

https://github.com/Shennoter/ApexRankLookUp/blob/8e96b0839f1fdf0f098c7d818e63e63b1fe164aa/src/main/kotlin/utils/MapReminder.kt#L77
中的`res.battle_royale.current.map`改为`res.battle_royale.next.map`。

**Comment by Shennoter** [comment]
收到，我自己没测试过，看没人反馈我还以为没问题呢
