### ISSUE TITLE
追猎指南中的最低排名显示错误

### ISSUE THREAD

**Issue by johnsilverhand** [Shennoter/ApexRankLookUp#19]
输入”/apexpred“指令 后显示的追猎指南图片中大逃杀和竞技场中的最低排名显示为-1
使用插件版本：1.5.3

**Comment by johnsilverhand** [comment]
![Cache_1a3bfaa89fc9f62a](https://user-images.githubusercontent.com/90089156/176937418-d714dbc2-3871-4a5f-9c26-7c5c36074290.jpg)

**Comment by Shennoter** [comment]
不是显示错误，显示-1是因为现在没有人上15000分，大师人数也不足750，意思就是只要是大师就是猎杀，所以不存在最低排名
