### ISSUE TITLE
1.6.0尝试编译缺少gradle-wrapper.properties文件

### ISSUE THREAD

**Issue by johnsilverhand** [Shennoter/ApexRankLookUp#20]
终端显示‘ApexRankLookUp-1.6.0\gradle\wrapper\gradle-wrapper.properties' does not exist.
尝试往ApexRankLookUp-1.6.0\gradle\wrapper目录下添加1.5.3的gradle-wrapper.properties文件后编译成功
但显示的jar包名字为“ApexLookUp-1.5.5.mirai2.jar” 而非“ApexLookUp-1.6.0.mirai2.jar”
现在调用 /apexbd 命令和 /apexreg 命令  机器人没有反应，不知道是不是因为这个的缘故

**Comment by Shennoter** [comment]
Release的源码是1.5.5的，有错误，抱歉。最新源码请直接clone main分支。
复制旧版的gradle-wrapper.properties文件是没有问题的，每个版本的这个文件都一样。idea的新版mirai插件没有自动添加这个文件，所以没有上传，我下次会加上。
