### ISSUE TITLE
可否将apex和apexid命令合并起来？

### ISSUE THREAD

**Issue by johnsilverhand** [Shennoter/ApexRankLookUp#21]
有个建议，如果调用/apexbd命令绑定后的QQ账号，可以在调用/apexid的命令时不填入id参数，机器人将自动查询已绑定的账号的信息。不需要额外学习调用命令/apex。这样对用户来说也许也比较方便

**Comment by Shennoter** [comment]
无法合并，/apexid使用mcl指令系统实现，/apex使用事件通道监听实现。指令系统无法获取指令发送者的qq号，不能实现将qq号与id绑定的功能。
