### ISSUE TITLE
绑定账号显示API key无权限或不存在

### ISSUE THREAD

**Issue by FXDYJ** [Shennoter/ApexRankLookUp#24]
![Snipaste_2022-12-10_08-49-17](https://user-images.githubusercontent.com/81761850/206819918-8fa06745-faa7-4157-bd9a-61dcdea8adc7.png)
![Snipaste_2022-12-10_08-49-38](https://user-images.githubusercontent.com/81761850/206819950-b882d004-fa3d-4356-be18-26a11a84f0e8.png)
2022-12-10 08:45:38 V/Bot.2819569319: [[CN]飞翔服务器-2周年周年庆活动开始！(951358735)] 飞翔到云间(3012287203) -> /apexbd Fx_owner
2022-12-10 08:46:03 V/Bot.2819569319: Group(951358735) <- api key无限限或不存在
2022-12-10 08:46:03 E/ApexLookUp: API key无权限或不存在

**Comment by FXDYJ** [comment]
补充：
![Snipaste_2022-12-10_09-22-13](https://user-images.githubusercontent.com/81761850/206821707-e469620e-1875-4f42-8a17-4f9547c57879.png)
![Snipaste_2022-12-10_09-22-47](https://user-images.githubusercontent.com/81761850/206821723-33757aed-e0c6-4d11-9ceb-17728b3ae995.png)

**Comment by Shennoter** [comment]
浏览器输入`https://api.mozambiquehe.re/maprotation?version=2&auth= ${apikey}`
测试是否有效
