### ISSUE TITLE
错误提示问题

### ISSUE THREAD

**Issue by geyuuu** [Shennoter/ApexRankLookUp#5]
源码逻辑应该默认只有请求过多 Error ，存在冒号时机器人给予失败回复。

使用中存在其他类型的 Error, 如对存在EA账号但是没有玩过Apex的情况，返回
`{"Error": "Player exists but has never played Apex Legends"}`
但机器人QQ回复仍然是“错误，短时间内请求过多,请稍后再试”。 建议修改一下回复内容，直接贴出api返回值也可。

**Comment by Shennoter** [comment]
```
     //抓取4xx错误
     try {  
        val url = "https://api.mozambiquehe.re/bridge?version=5&platform=PC&player=$id&auth=$apiKey"  
        requestStr = URL(url).readText()
    }catch (e:Exception){
        val excp = e.toString()
        if (":" in excp){
            code = "错误，短时间内请求过多,请稍后再试"
        }
        RankLookUp.logger.error(code)
        return code
    }
    //抓取查询错误
    if (requestStr.contains("Error")){
        var errorInfo = ""
        val res = Gson().fromJson(requestStr, ApexResponseError::class.java)
        errorInfo = "查询出错：" + res.Error
        return errorInfo
    }
```
这个try其实只是用来抓请求过多error的，因为请求过多时api会返回4xx错误，是一个Exception，但是玩家不存在这类错误并不是Exception，在try代码块下面还有一段，会把这类错误作为ApexResponseError数据类储存，然后回复api返回的错误原因，如图
![微信截图_20220408164834](https://user-images.githubusercontent.com/36178491/162400620-4422cc5a-09df-47c2-af92-a6970c299d11.png)
我测试了一个叫playernotfound的id，用浏览器访问和终端curl结果和你这个一样都是
`{"Error": "Player exists but has never played Apex Legends"}`
但是在ide里面debug报错是
`java.io.FileNotFoundException: https://api.mozambiquehe.re/bridge?version=5&platform=PC&player=playernotfound&auth=FsKmkWPMRJlOEmW8H3ZN`
具体为什么这样我目前还没搞清楚

**Comment by Shennoter** [comment]
我知道问题原因了，api返回`{"Error": "Player exists but has never played Apex Legends"} `的时候，响应状态码是404，响应包是空的，程序认为这个页面为空就抛出了FileNotFoundException，但是实际上页面是包含信息的。
然而返回`{"Error"："player shhdncmc not found (code 103 - skipping origin backup api)}"`的时候状态码是200

**Comment by rabbit-dayi** [comment]
好像这个问题还是没有修好的样子？

**Comment by Shennoter** [comment]
> 好像这个问题还是没有修好的样子？

现在”错误，短时间内请求过多,请稍后再试“确实是被限流了，请求这种类型的id经常这样，就算用浏览器也是，api问题
状态码429`{"Error":"Slow down ! You're being throttled."}`
状态码405`{"Error": "Your request has been declined because of server load issue, Origin refusing the connection or a wrong username."}`
这两种都会作为Exception被捕获
就算是我第一次用浏览器请求都会出现这种错误

**Comment by Shennoter** [comment]
重构了请求方法，现在可以根据状态码返回详细准确的错误信息
